name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build & Run Development Container
        uses: devcontainers/ci@v0.2
        with:
          push: true
          imageName: ghcr.io/customink/crypteia-devcontainer
          cacheFrom: ghcr.io/customink/crypteia-devcontainer
          env: |
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_SESSION_TOKEN
            AWS_DEFAULT_REGION
            AWS_REGION
          runCmd: |
            ./bin/setup
            ./bin/test
      - name: Build & Run Development Container (w/Amazon Linux)
        uses: devcontainers/ci@v0.2
        with:
          push: true
          imageName: ghcr.io/customink/crypteia-devcontainer
          cacheFrom: ghcr.io/customink/crypteia-devcontainer
          runCmd: |
            ./amzn/setup
            ./amzn/test
      - name: Build & Run Development Container (w/ Python)
        uses: devcontainers/ci@v0.2
        with:
          push: true
          imageName: ghcr.io/customink/crypteia-devcontainer
          cacheFrom: ghcr.io/customink/crypteia-devcontainer
          env: |
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_SESSION_TOKEN
            AWS_DEFAULT_REGION
            AWS_REGION
          runCmd: |
            ./py27/setup
            ./py27/test
