name: Test
on: [push, workflow_dispatch]
jobs:
  image:
    name: Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/rails-lambda/crypteia-ci
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: echo DONE!
  debian-x86-64:
    name: Debian x86_64
    runs-on: ubuntu-22.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: |
            ./bin/setup
            ./bin/test-local
  debian-arm64:
    name: Debian arm64
    runs-on: ubuntu-22.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: |
            ./debian/setup-arm64
            ./debian/test-arm64
  amazon-x86-64:
    name: AmazonLinux2/x86_64
    runs-on: ubuntu-22.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: |
            ./amzn/setup
            ./amzn/test
  amazon-arm64:
    name: AmazonLinux2 arm64
    runs-on: ubuntu-22.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: |
            ./amzn/setup-arm64
            ./amzn/test-arm64
  ubuntu-py27:
    name: Ubuntu x86_64 (Python27)
    runs-on: ubuntu-22.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: |
            ./py27/setup
            ./py27/test
  amazonlinux2023-x86-64:
    name: AmazonLinux2023/x86_64
    runs-on: ubuntu-22.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: |
            ./amzn2023/setup
            ./amzn2023/test
  amazonlinux2023-arm64:
    name: AmazonLinux2023 arm64
    runs-on: ubuntu-22.04
    needs: image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test
        uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/crypteia-ci
          runCmd: |
            ./amzn2023/setup-arm64
            ./amzn2023/test-arm64
